---
# =============================================================================
# 
# =============================================================================
environment: staging

flags:
  node:
    outgoing_channels_balances: 30s

    healthcheck: 15s
    retrieve_peers: 1m
    refresh_balances: 5m
    refresh_redeemed: 5m
    relay_messages: On
    retrieve_balances: 5m

    observe_message_queue: On
    maintain_sessions: 15s

  peer:
    message_relay_request: Off
    
# =============================================================================
# 
# =============================================================================
economic_model:
  legacy:
    proportion: 1.0
    apr: 0.000001

    coefficients:
      a: 1
      b: 1.4
      upperbound: "15 wxHOPR"
      lowerbound: "0.1 wxHOPR"

  sigmoid:
    proportion: 0
    max_apr: 0.0000001
    network_capacity: 100
    total_token_supply: "5000 wxHOPR"

    offset: 10
    buckets:
      economic_security:
        flatness: 1.65
        skewness: 1.50
        upperbound: 0.75
        offset: 0

      network_capacity:
        flatness: 10.0
        skewness: 2.75
        upperbound: 1.0
        offset: 0

# =============================================================================
# 
# =============================================================================
peer:
  minimum_delay_between_batches: 10s
  sleep_mean_time: 10s
  sleep_std_time: 2s
  excluded_peers: # TODO

# =============================================================================
# 
# =============================================================================
channel:
  min_balance: "0.05 wxHOPR"
  funding_amount: "0.1 wxHOPR"
  max_age: 1d

# =============================================================================
#
# =============================================================================
sessions:
  green_destinations: # TODO
  blue_destinations: # TODO
  session_retry_base_delay: 2s
  session_retry_max_delay: 60s
  message_worker_count: 10
  message_queue_maxsize: 10000

# =============================================================================
#
# =============================================================================
...
