---
# =============================================================================
# 
# =============================================================================
environment: prod

flags:
  node:
    healthcheck: 15s
    retrieve_peers: 1m
    relay_messages: On
    retrieve_balances: 5m
    
    observe_message_queue: On
    maintain_sessions: 15s

# =============================================================================
# 
# =============================================================================
incentive:
  min_outgoing_channels: 5
  min_channel_balance: "100 wxHOPR"
  burst_rate: 30                  # Mbit/s
  burst_duration: 10s
  target_relayer_interval: 600s   # average time between two bursts to the same relayer, across all CT nodes
  max_concurrent_bursts_per_ct: 0 # 0 = no limit
  ct_node_count: 5                # CT nodes in the deployment

# =============================================================================
# 
# =============================================================================
peer:
  excluded_peers: []
  
# =============================================================================
#
# =============================================================================
sessions:
  green_destinations: 
    - "0x51624c828c175cc81d6a7dd22a9a30d68c6a1ae0"
    - "0xa64109ed980c902ac554662b9d569a6a3f71e7a7"
    - "0x02d7d9ca7788e674676f809ac984cbf59e4b6099"
    - "0x50eac8e328847e5389aabb267398386db7225644"
    - "0x991a376c646274d74adb3b25ccc292a775f352f1"
  blue_destinations: []
  session_retry_base_delay: 2s
  session_retry_max_delay: 60s
  message_worker_count: 10
  message_queue_maxsize: 10000
  receive_timeout: 5s

# =============================================================================
#
# =============================================================================
...
