---
# =============================================================================
# 
# =============================================================================
flags:
  core:
    healthcheck: 30
    check_subgraph_urls: 30
    get_fundings: 30
    get_ticket_price: 30
    aggregate_peers: 30
    get_topology_data: 30
    get_subgraph_data: 30
    get_registered_nodes: 30
    get_nft_holders: 30
    get_peers_rewards: 30
    apply_economic_model: 30
    distribute_rewards: ~
    
  node:
    healthcheck: 30
    retrieve_peers: 30
    retrieve_incoming_channels: 30
    retrieve_outgoing_channels: 30
    retrieve_balances: 30
    open_channels: ~
    close_old_channels: ~
    close_pending_channels: ~
    fund_channels: ~
    close_incoming_channels: ~
    get_total_channel_funds: ~
    
# =============================================================================
# 
# =============================================================================
distribution:
  min_eligible_peers: 500
  max_apr_percentage: 15.0
  message_delivery_delay: 10.0
  delay_between_two_messages: 0.2
  max_iterations: 6

# =============================================================================
# 
# =============================================================================
gcp:
  file_prefix: expected_reward
  folder: refactored_app
  bucket: ct-platform-ct

# =============================================================================
# 
# =============================================================================
economic_model:
  filename: parameters-production.json
  min_safe_allowance: -1
  nft_threshold: ~

# =============================================================================
# 
# =============================================================================
peer:
  min_version: '2.0.7'


# =============================================================================
# 
# =============================================================================
channel:
  min_balance: 0.05
  funding_amount: 0.2
  max_age_seconds: 60

# =============================================================================
# 
# =============================================================================
rabbitmq:
  task_name: fake_task
  project_name: ct-app

# =============================================================================
# 
# =============================================================================
subgraph:
  safes_balance:
    query_id: FEQcaX9qfh31YL2K7rxRN5a3sr9rjMWkguJnby7StNRo
    url_backup: https://api.studio.thegraph.com/query/40439/hopr-nodes-dufour/version/latest

  staking:
    query_id: DrkbaCvNGVcNH1RghepLRy6NSHFi8Dmwp4T2LN3LqcjY
    url_backup: https://api.studio.thegraph.com/query/40439/hopr-stake-all-seasons/v0.0.10
  
  wxhopr-txs:
    query_id: ~
    url_backup: https://api.studio.thegraph.com/query/58438/wxhoprtransactions/v0.0.6
  
  rewards:
    query_id: Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj
    url_backup: https://api.studio.thegraph.com/query/40439/hopr-channels/version/latest
...