---
# =============================================================================
# 
# =============================================================================
flags:
  core: 
    healthcheck: 60
    checkSubgraphURLs: 300
    getTicketPrice: 120
    aggregatePeers: 300
    getTopologyData: 300
    getSubgraphData: 300
    getRegisteredNodes: 300
    getNFTHolders: 300
    getPeersRewards: 300
    applyEconomicModel: 120
    distributeRewards: 1
    
  node:
    healthcheck: 60
    retrievePeers: 300
    retrieveIncomingChannels: 600
    retrieveOutgoingChannels: 600
    retrieveBalances: 900
    openChannels: 300
    closeOldChannels: 300
    closePendingChannels: 1800
    fundChannels: 300
    closeIncomingChannels: ~
    getTotalChannelFunds: 900
    
# =============================================================================
# 
# =============================================================================
economicModel:
  minSafeAllowance: -1
  maxAPRPercentage: 15.0
  NFTThreshold: 30000

  coefficients:
    a: 1
    b: 1.4
    c: 75000
    l: 10000
  
  equations: 
    fx: 
      formula: "a * x"
      condition: "l <= x <= c"
    gx:
      formula: "a * c + (x - c) ** (1 / b)"
      condition: "x > c"
  
  budget:
    # one distribution every 30min
    amount: 190000
    period: 2628000 # in seconds
    s: 1
    countsInPeriod: 1460
    winningProbability: 1

# =============================================================================
# 
# =============================================================================
distribution:
  minEligiblePeers: 100
  messageDeliveryDelay: 5.0
  delayBetweenTwoMessages: 0.0001
  maxIterations: 2

# =============================================================================
# 
# =============================================================================
peer:
  minVersion: '2.0.7'

# =============================================================================
# 
# =============================================================================
channel:
  minBalance: 15
  fundingAmount: 35
  maxAgeSeconds: 172800

# =============================================================================
# 
# =============================================================================
subgraph:
  safesBalance:
    queryID: GP2abJCarirMJCanuk4SBmnadiobEWH9ME2MNRAHbBTp
    URLBackup: https://api.studio.thegraph.com/query/78696/hopr-nodes-dufour/version/latest

  staking:
    queryID: F1NZayy7TXRi2szAVXvMFfJuC9uSdNYLUPAb6p6BYRmZ
    URLBackup: https://api.studio.thegraph.com/query/78696/hopr-stake-all-seasons/version/latest
  
  rewards:
    queryID: GoJ4KRuYEcELQk42hir2tjau6r1u4ibDFY6t1zH6zpKk
    URLBackup: https://api.studio.thegraph.com/query/78696/hopr-channels/version/latest
...