---
# =============================================================================
# 
# =============================================================================
flags:
  core: 
    healthcheck: 10
    checkSubgraphURLs: 30
    getFundings: 30
    getTicketPrice: 30
    aggregatePeers: 30
    getTopologyData: 30
    getSubgraphData: 30
    getRegisteredNodes: 30
    getNFTHolders: 30
    getPeersRewards: 30
    applyEconomicModel: 30
    distributeRewards: ~

    
  node:
    healthcheck: 10
    retrievePeers: 30
    retrieveIncomingChannels: 30
    retrieveOutgoingChannels: 30
    retrieveBalances: 30
    openChannels: ~
    closeOldChannels: ~
    closePendingChannels: ~
    fundChannels: ~
    closeIncomingChannels: ~
    getTotalChannelFunds: ~
    
# =============================================================================
# 
# =============================================================================
economicModel:
  minSafeAllowance: -1
  maxAPRPercentage: 15.0
  NFTThreshold: ~

  coefficients:
    a: 1
    b: 1
    c: 3
    l: 0
  
  equations: 
    fx: 
      formula: "a * x"
      condition: "l <= x <= c"
    gx:
      formula: "a * c + (x - c) ** (1 / b)"
      condition: "x > c"
  
  budget:
    amount: 400
    period: 1200
    s: 0.25
    countsInPeriod: 1
    ticketPrice: 0.5 # deprecated
    winningProbability: 1

# =============================================================================
# 
# =============================================================================
distribution:
  minEligiblePeers: 500
  messageDeliveryDelay: 10.0
  delayBetweenTwoMessages: 0.2
  batchSize: 100
  maxIterations: 6

# =============================================================================
# 
# =============================================================================
gcp:
  filePrefix: expected_reward
  folder: refactored_app
  bucket: ct-platform-ct

# =============================================================================
# 
# =============================================================================
peer:
  minVersion: '2.0.7'

# =============================================================================
# 
# =============================================================================
channel:
  minBalance: 0.05
  fundingAmount: 0.2
  maxAgeSeconds: 60

# =============================================================================
# 
# =============================================================================
rabbitmq:
  taskName: fake_task
  projectName: ct-app

# =============================================================================
# 
# =============================================================================
subgraph:
  safesBalance:
    queryID: FEQcaX9qfh31YL2K7rxRN5a3sr9rjMWkguJnby7StNRo
    URLBackup: https://api.studio.thegraph.com/query/40439/hopr-nodes-dufour/version/latest

  staking:
    queryID: DrkbaCvNGVcNH1RghepLRy6NSHFi8Dmwp4T2LN3LqcjY
    URLBackup: https://api.studio.thegraph.com/query/40439/hopr-stake-all-seasons/v0.0.10
  
  wxHOPRTxs:
    queryID: ~
    URLBackup: https://api.studio.thegraph.com/query/58438/wxhoprtransactions/v0.0.6
  
  rewards:
    queryID: ~ #Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj
    URLBackup: https://api.studio.thegraph.com/query/40439/hopr-channels/version/latest
...