{
 "title": "CT Core",
 "tags": [
  "Home",
  "CT"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "type": "canvas", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (token) (ct_balance{token=\"safe_hopr\"}) / 1e18",
     "legendFormat": "Safe stake"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg(ct_balance{token=\"safe_hopr\"})) / (-1 * avg(sum by (peer_id)(delta(ct_balance{token=\"safe_hopr\"}[1d])))) / 1",
     "legendFormat": "Runway (est.)"
    },
    {
     "expr": "(-1 * avg(sum by (peer_id)(delta(ct_balance{token=\"safe_hopr\"}[1d])))) / 1e18",
     "legendFormat": "Cost / day (est.)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ct_subgraph_in_use{slug=\"subgraph-wxhopr-txs\"}) == bool 0",
     "legendFormat": "Claimed amount status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ct_total_funding) - sum(ct_channel_funds) - avg(ct_balance{token=\"safe_hopr\"}) / 1e18 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "target" },
    {
     "expr": "3600 * sum (1 / (ct_peer_delay != 0))",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"sent\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"received\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ct_eligible_peers != 0)", "legendFormat": "Eligible for CT" },
    { "expr": "sum(ct_nft_holders != 0)", "legendFormat": "NFT holders" },
    { "expr": "sum(ct_topology_size != 0)", "legendFormat": "Possible relayers" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ct_unique_peers{type=\"known\"} != 0)",
     "legendFormat": "Known"
    },
    {
     "expr": "sum(ct_unique_peers{type=\"unreachable\"})",
     "legendFormat": "Unreachable"
    },
    {
     "expr": "sum(increase(ct_unique_peers{type=\"new\"}[$__range]))",
     "legendFormat": "New"
    }
   ]
  },
  { "title": "Message queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (ct_queue_size)",
     "legendFormat": "Messages in queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(1 / (ct_peer_delay != 0))", "legendFormat": "Exp. throughput" },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"sent\"}[$__rate_interval]))",
     "legendFormat": "Sent messages"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"received\"}[$__rate_interval]))",
     "legendFormat": "Received messages"
    }
   ]
  },
  { "title": "Subgraph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (slug) (ct_subgraph_in_use)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls per hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (slug) (rate(ct_subgraph_calls[$__range])) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Node status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (peer_id) (ct_node_health)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels funds (wxHOPR)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (ct_channel_funds)",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Node funds (xDai)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (ct_balance{token=\"native\"}) / 1e18",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Visible peers on 2.1.5+",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (ct_peers_count) != 0",
     "legendFormat": "{{token}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Channels fund",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (increase(ct_channel_operation{op=\"fund\"}[$__range])) != 0",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Channels opened",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (increase(ct_channel_operation{op=\"opened\"}[$__range])) != 0",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (method, exported_endpoint) (increase(hopr_http_api_call_count{namespace=\"ctdapp\" ,status!~\"[1,2,3].*\"}[10m]))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Pending channels closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (increase(ct_channel_operation{op=\"pending_closed\"}[$__range])) != 0",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Channels closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (increase(ct_channel_operation{op=\"old_closed\"}[$__range])) != 0",
     "legendFormat": "{{token}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } }
 ]
}