{
 "title": "CT Distribution",
 "tags": [
  "Home",
  "CT"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "sender",
    "query": {
     "query": "label_values(ct_messages_delays_bucket,sender)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sent and relayed messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "3600 * sum (1 / (ct_peer_delay != 0))",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"sent\"}[$__rate_interval])) * 3600",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"received\"}[$__rate_interval])) * 3600",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Relayed / expected per version",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (relayer) (3600 / (label_replace(ct_peer_delay,\"relayer\", \"$1\", \"peer_id\", \"(.*)\") > 0)) * on(relayer) group_right() (sum by (relayer, version) (label_replace(ct_peer_version ,\"relayer\", \"$1\", \"peer_id\", \"(.*)\"))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (relayer) (rate(ct_messages_stats{namespace=\"ctdapp\", type=\"relayed\"}[$__rate_interval])) * 3600 * on(relayer) group_right() (sum by (relayer, version) (label_replace(ct_peer_version ,\"relayer\", \"$1\", \"peer_id\", \"(.*)\"))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "target" },
    {
     "expr": "3600 * sum (1 / (ct_peer_delay != 0))",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"sent\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(hopr_packets_count{namespace=\"ctdapp\", type=\"received\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    }
   ]
  },
  {
   "title": "Eligible peers",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (peer_id, version) (label_replace(ct_peer_version, \"version_parsed\", \"$1\", \"version\", \"^(\\\\d+\\\\.\\\\d+\\\\.\\\\d+[a-z]*\\\\d*).*\")) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (peer_id) (ct_peer_delay > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node's stake distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ct_peer_stake{type=\"balance\"}",
     "legendFormat": "stake"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "365 * 86400 * sum( 1/ (ct_peer_delay != 0)) * sum(ct_ticket_stats{type=\"price\"} != 1) * sum(ct_ticket_stats{type=\"win_prob\"}) / sum(ct_peer_stake{type=\"split\"})",
     "legendFormat": "Average APR"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Messages loop-back delays from ...",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  { "title": "$sender", "type": "text", "gridPos": { "h": 1, "w": 4.8, "x": 0, "y": 16 }, "repeat": "sender" },
  {
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 4.8, "x": 0, "y": 17 },
   "repeat": "sender",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ct_messages_delays_bucket{sender=\"$sender\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 32 },
   "repeat": "sender",
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ct_messages_delays_bucket{sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantile 50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ct_messages_delays_bucket{sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantile 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ct_messages_delays_bucket{sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantile 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ct_messages_delays_bucket{sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantitle 99%"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  { "title": "Distribution statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "... by peer ID for the last period",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": " sum by (relayer) (3600 / label_replace(ct_peer_delay,\"relayer\", \"$1\", \"peer_id\", \"(.*)\") != 0)",
     "legendFormat": "expected"
    },
    {
     "expr": "sum by (relayer) (rate(ct_messages_stats{namespace=\"ctdapp\", type=\"relayed\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    },
    {
     "expr": "sum by (relayer) (rate(ct_messages_stats{namespace=\"ctdapp\", type=\"sent\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    },
    {
     "expr": "sum by (relayer, version) (label_replace(ct_peer_version ,\"relayer\", \"$1\", \"peer_id\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (relayer) (rate(ct_messages_delays_sum[$__rate_interval])\n/ \nrate(ct_messages_delays_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}