{
 "title": "[deprecated] CT Rewards by peerID",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "peer_id", "label": "Peer ID" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ct_peer_delay{peer_id=\"$peer_id\"})",
     "legendFormat": "Message interval"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wxHOPR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ct_peer_stake{ peer_id=\"$peer_id\"})",
     "legendFormat": "Stake"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ct_peer_version{peer_id=\"$peer_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ct_peer_safe_count{peer_id=\"$peer_id\"})",
     "legendFormat": "Node pool size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "365 * 24 * 60 * 60 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"} != 0) * sum by (namespace) (ct_ticket_stats{type=\"price\"} != 1) / sum by (namespace) (ct_peer_stake{peer_id=\"$peer_id\", type=\"split\"})",
     "legendFormat": "APR"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "3600 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"})",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"relayed\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"} != 0)",
     "legendFormat": "Expected rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ct_messages_stats{relayer=\"$peer_id\", type=\"sent\"}[$__rate_interval])) * 60",
     "legendFormat": "Sent to"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ct_messages_stats{relayer=\"$peer_id\", type=\"relayed\"}[$__rate_interval])) * 60",
     "legendFormat": "Relayed by"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "In-depth message graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Issuer proportions",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sender) (rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[1h]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Send and relay counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "3600 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"})",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"relayed\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    }
   ]
  },
  {
   "title": "Send and relay ratios",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "1", "legendFormat": "target" },
    {
     "expr": "3600 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"})",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"relayed\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    }
   ]
  }
 ]
}