{
 "title": "CT Reward per safe",
 "tags": [ "CT" ],
 "time": { "from": "now-3h/h", "to": "now" },
 "templating": {
  "list": [
   { "name": "safe", "label": "Safe address" },
   {
    "name": "peer_id",
    "label": "Peer ID",
    "query": {
     "query": "label_values(ct_peer_safe_count{safe=\"$safe\"},peer_id)"
    }
   },
   {
    "name": "address",
    "query": {
     "query": "label_values(ct_address_pairs{peer_id=\"$peer_id\"},address)"
    }
   },
   {
    "name": "sender",
    "query": {
     "query": "label_values(ct_messages_delays_bucket,sender)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Associated nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (peer_id, version) (ct_peer_version) + on(peer_id) group_left() sum by (peer_id)(ct_peer_safe_count{safe=\"$safe\", safe!=\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (peer_id) (ct_peer_delay) + on(peer_id) group_left() sum by (peer_id)(ct_peer_safe_count{safe=\"$safe\", safe!=\"\"}) - on(peer_id) group_left() sum by (peer_id)(ct_peer_safe_count{safe=\"$safe\", safe!=\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (peer_id, address) (ct_address_pairs) + on(peer_id) group_left() sum by (peer_id)(ct_peer_safe_count{safe=\"$safe\", safe!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wxHOPR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (safe) (ct_peer_stake{safe=\"$safe\", type=\"balance\"})",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wxHOPR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (safe) (ct_peer_stake{safe=\"$safe\", type=\"allowance\"})",
     "legendFormat": "Allowance"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Extra balance from the allocation schedule (investors only)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wxHOPR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (safe) (ct_peer_stake{safe=\"$safe\", type=\"additional_balance\"})",
     "legendFormat": "Additional balance"
    }
   ]
  },
  {
   "title": "Packet loop-back delay",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ct_messages_delays_bucket{relayer=\"$peer_id\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ct_messages_stats{relayer=\"$peer_id\", type=\"relayed\"}[$__rate_interval])) * 60",
     "legendFormat": "Relayed by"
    }
   ]
  },
  {
   "title": "Send and relay counts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "3600 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"})",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"relayed\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "3600 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"})",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"relayed\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "relayed"
    },
    {
     "expr": "sum(rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[$__rate_interval])) * 3600",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / sum by (namespace) (ct_peer_delay{peer_id=\"$peer_id\"} != 0)",
     "legendFormat": "Expected rate"
    }
   ]
  },
  {
   "title": "Issuer proportions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sender) (rate(ct_messages_stats{type=\"sent\", relayer=\"$peer_id\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. msg delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ct_messages_delays_sum{relayer=\"$peer_id\"}[$__rate_interval])\n/ \nrate(ct_messages_delays_count{relayer=\"$peer_id\"}[$__rate_interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ct_messages_stats{relayer=\"$peer_id\", type=\"sent\"}[$__rate_interval])) * 60",
     "legendFormat": "Sent to"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Packet loop-back delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "$sender", "type": "text", "gridPos": { "h": 1, "w": 4.8, "x": 0, "y": 19 }, "repeat": "sender" },
  {
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 4.8, "x": 0, "y": 20 },
   "repeat": "sender",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ct_messages_delays_bucket{relayer=\"$peer_id\", sender=\"$sender\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 35 },
   "repeat": "sender",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ct_messages_delays_bucket{relayer=\"$peer_id\", sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantile 50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ct_messages_delays_bucket{relayer=\"$peer_id\", sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantile 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ct_messages_delays_bucket{relayer=\"$peer_id\", sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantile 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ct_messages_delays_bucket{relayer=\"$peer_id\", sender=\"$sender\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Quantitle 99%"
    }
   ]
  }
 ]
}