wallet:
    deployerPrivateKey: ENC[AES256_GCM,data:YSbqFo0lY06f/YwbpLORr4OEUI9CK2grE52KpqNJfI92pAsW8e/eMvCZQff9lKIriAVPobUZmRA8RbgzLUlObg==,iv:7Y1FZiWbBwUxm+w8Lwsc1ENnFLEKqYTVcM3LtXLwPf8=,tag:8NiY+R/8/mCjyELuGPCxbA==,type:str]
    identityPassword: ENC[AES256_GCM,data:G8BYV1Xh2ZUqNrRtI1Bq+58IwHKearM=,iv:g97XFgztPxdbcsaqDzpXFoAbH44jflxW62TcC/urSkM=,tag:eujRShbzmOzH7mB640az+g==,type:str]
    hoprdApiToken: ENC[AES256_GCM,data:oo1BU9BT4MGuqYtzu6plY48EcWgr3cmJAfBykMOudzEJPPW4ugb6vqWlLAlrOEYC9mVM9Q==,iv:eHEh4Ul5Cw8HxbunANrBTLQ0q9PNKyhxgvO9nAcL5bg=,tag:LpwNpPyT9NzsE5rig3n0SQ==,type:str]
#ENC[AES256_GCM,data:/bN4qcaF3C4REQgitRFtffY=,iv:Fvsn8Jnp0zSPZRCl8DHxqVI7dg40nhPICAQnszpoZik=,tag:ZdcNTxyLDbPPdIZITuW71w==,type:comment]
ctdapp:
    postgres:
        database: ENC[AES256_GCM,data:BVZc3fdB,iv:9/KciG4PXOnUD7OL8yccwe0e5wc8txiajaNiGmN9LkU=,tag:+9Xq2PxdghMyMXoC3D+AzQ==,type:str]
        host: ENC[AES256_GCM,data:x/aX486Lo3MTjANMR7XW9BumY23G+hC8,iv:OvqK5FhF5oVAje9fuT902R1bLLaVTi8au3fDRAZBYsk=,tag:Y5Y3sLdD0Qwy4f+hj9K05w==,type:str]
        password: ENC[AES256_GCM,data:4AkaK6xA8R541rr782+TGS06i8K6rBsU59SDSf+ek+WYzwGYOjKQdM/lflp0G9fNq9fi9q2Flp9moDy7dbybvA==,iv:Epecgv2hUWbi+JbRLd2iEEd41i+Yi37kosmlaz8UeTY=,tag:5tqoRlZNnDRXtck6XwY/vw==,type:str]
        port: ENC[AES256_GCM,data:pvfJaA==,iv:ShElefgn2+t5nVWnzUCn20HSuEHlZvhtkso90b9fauk=,tag:h1N8vScNa3CosIkNoICVag==,type:str]
        username: ENC[AES256_GCM,data:5ryVlszO,iv:zrJp8u4krDji4dyNlJVPBFVAa9WH/jj2piVYypasGL8=,tag:9HG294qr+ty2JAkJhjpi3Q==,type:str]
    rabbitmq:
        celeryBrokerUrl: ENC[AES256_GCM,data:wD44RW5ae2vBj80pw3f+8KGB0sPPUPpJH3cCWmGLN1VKBDj5GXwYw2g3sawZfkV9TWQxmM3uwEs2+AYDHeaTPVu4SD8v5/we35HWBeZofCAru9qWCcV0iGSddDPNOvfIy+7MO8szOVq11dPlDsUYnU/50e+h5A==,iv:aFnCb0FWpCN0QN4HbXETsAGED9VnXMJ3Jj3g1USWtAI=,tag:ebbUx1F+O+1LhM0JCTlZ8g==,type:str]
        host: ENC[AES256_GCM,data:vQJeCSpcfjEPIUtO4hddzCISRjaz4j0izzMtjY/P1tU=,iv:AayENCFr9E20Hx67IDKT7GORgpDCXsYQKQv7MpnP3zU=,tag:mMIaz487cVIrDgDwCN+tqw==,type:str]
        password: ENC[AES256_GCM,data:V/o5ALusfHIAEUfog2F1VAcj34nJF6FhJzw11DUpzmcmzoW59Ehz5o1bYwGJ2BQ6O1Di8n8Cte5JjOI7zy1bmA==,iv:qiN6RXnl/4Y+9I2OkZng4MbvhX8xt76PHnhAbZU6RJQ=,tag:1inGOBbqbQwTahygkjXp1g==,type:str]
        username: ENC[AES256_GCM,data:OqAIlMBH,iv:WrX+6GPjqybbUsz3m8wN4jRkqZDQWUKeDKXp/5P3eBU=,tag:7D4VryqUGpeBzTivsdJFlQ==,type:str]
        virtualhost: ENC[AES256_GCM,data:X7AiK8Wr,iv:p0Uo1xGlBmzWsOCrTenE3QdSFs/DJPYQ2g1Nb35hSFM=,tag:wVxKa8yM++RV2HPVs8yLpA==,type:str]
    subgraph:
        stakingUrl: ENC[AES256_GCM,data:R3oT6qp39hbIzJzQXwrO7rU+zb96T5neQqQ+c/LMLD9qn0Cw02qU4u6KobmrzawwBOEIpRRVjOoGiFiMO8PDUwOh5xZIDnk6s0PEhR8PL74CJZNjaZDwt/S/0tty8aoB8gH3hK1Uk6f77rozya96v+0Qkbv2wnPK+nLg,iv:Gbv5ogwaWsTEBDGqTigR5QPJVI6CEIJQOwkkDeq246g=,tag:HM6ptK3hixXhMHlMNW4jOQ==,type:str]
        stakingUrlBackup: ENC[AES256_GCM,data:xvqh3/VU9oXHtH6ej14+RP11Tw8wwk+QJh9b3k9vUUyPB36Ecq+sm8JKyLds36Qs/61UHlTPBwy6i+oKegvOIzShqzSZPN9safo=,iv:SX+82FWti3A0PliUUgZoaQiEjhz9MDmfoBCxgefUNX8=,tag:Ck4GT/CKq91CGT9wKewudA==,type:str]
        safesBalanceUrl: ENC[AES256_GCM,data:K/dqFhJMKc8pCSiFtcrUqE+G7LEhwi65/67rfGzCiOdjl2Mo9RR4kFI/yNPvauYsycur81zOIQ/efMvlRaqfxFvfRGAOal179BLewV8KscqEVolzamfeW9g35RCtS2yTwFb2XsWTFMFZuobX07QmPr1znXtfExM8nW14,iv:T/h9G5yuL0Q4DZF0PdGpfRT/ENicaDUNDizOjDZU8Fk=,tag:xoYXlnqwHfmFKaO6fQMqgA==,type:str]
        safesBalanceUrlBackup: ENC[AES256_GCM,data:t0g6/kq6CNXqL6Su9j+M0lVWqjMMHU44mdFtwVS/yY7Z7t0D77Bqr4BvCbFWBlQ1E2vkIc5iRZ/67ErrH3Ge/R/ocOS2c+NfNVDILQ==,iv:HyRmsnKXmkfyBRLOBBiyyiKuKuFmQh10hPhtxq1FnuA=,tag:vB2HygASXoY8FATgIBW+tA==,type:str]
        wxhoprTxsUrl: ENC[AES256_GCM,data:Pr7W99U2r13NZFRw6haifYI38Pse/6lpe5EewSTnhmjRrzV+igrRzPAykCUOwtpqgMO95anxbj0JEeEQWdjBacCjrDuM1AU46wDUUq/ufVMs/X09FePCme8TDHLC6ke/2j5d7Vru7GZQ0LcsfUTYxio2/1ro6Qo4Kqqw,iv:zJtuDEGbizi84IlbY/b8Qk7Nc4eAmf6urODQbXU64f4=,tag:SrR8Dhzm0GWVqvjTqKNjyg==,type:str]
        wxhoprTxsUrlBackup: ENC[AES256_GCM,data:l5ErOWItJN8y2ZeplUE5NqyzOMTjhqWTYJjJHGDXAobjQ3AHkGAIGWycGNyLRw0H6enHATdlAbmPLBqPtXtHmYHZLymb,iv:trt2185Yb80q41ieGvGH58npuH0fFSoBYwxVX48mCpc=,tag:VxgafnXrrTG3Cb2bT8bLGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx5540pah2npkghtwey6r6xzq6nms6z8h9864ml6m289wh0q8g7qw282xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVUwcUpxQ3hTNDgwelBy
            Y0RGVXp5MVIwWVdISGtPaVpqV2pCdjNQMjBRCmQwdVBtRFZISG5vUm1tWXpYeDJN
            NDZyb3dsQkJ6aVFNUlNVYzdhMkIxM2MKLS0tIFppS0VsQlE1OHBQVkRzRkVjSGxn
            MlBDUE1hYnJOVk9CYzloT0loME1SQWcKrn5RO5anAmI0lJH4IsO285N6sNK46/NM
            D+3ogpa+95AiuncxB3zCsiq/gfwDqCfA5eVdYeo/ygIyiCGm2018XA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12p3svcjz26wqaw2ccxarwd22fuaxdzhn57em9mlyjvh2vvjvresqcejfwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyamEzL1VFQjg2Sm9yTFMv
            QjE5L0ZlMGMwSXBGaDRrVC9lNlEyaUdCY1drCkd6VXV2dTdKMi92SE1BUmI5Vzdt
            Y3JFNnhvRXp3cmJNK3hXdG1tZHZmbWMKLS0tIG94YWRRMXgvUmkwWE5PaktFMkVG
            M1ZjcTlDVWYrbUYwQU9DUlN0NVhUY0kKyUI2VVCMfx+squtawdgIvQvgpmMeQOnd
            LmVJsOGerMfUsUcOv3p99jgqP2t8vsmxHx7bUe1yIUDr54LSfL/2Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T13:58:09Z"
    mac: ENC[AES256_GCM,data:uYAO0jsPH2b9GbWlG0FzbD/KfGytDhAhDEQZ16YhhR5KZob7Eq1TILtFo6LuZO4EMB7Bk/PZ3GQxo5+9cdzITtzpe3T9zS/NB2WCzii6Qx7FuwE+PfZVM4p9jCxGf9Hf1AFvBBwjfRU6MB3BdWiKYmV5aGq9RfEQBVf03hEQrRI=,iv:jYzrMV04E2IMZAUISB5LKPPlb4kPL2s4MAeETeTdxLc=,tag:J+LHMQ/j+WO8+cBSYnH2uQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
