replicas: 5
network: rotsee
version: saint-louis-latest

config: |
  hopr:
    chain:
      network: rotsee
      provider: https://gnosis-chain.rpc.rank1.co
    strategy:
      on_fail_continue: true
      allow_recursive: false
      strategies: []

identities:
  ctdapp-green-node-1:
    identityFile: ""
    peerId: ""
    nativeAddress: ""
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-2:
    identityFile: ""
    peerId: ""
    nativeAddress: ""
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-3:
    identityFile: ""
    peerId: ""
    nativeAddress: ""
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-4:
    identityFile: ""
    peerId: ""
    nativeAddress: ""
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-5:
    identityFile: ""
    peerId: ""
    nativeAddress: ""
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"