blue-nodes:
  enabled: true
green-nodes:
  enabled: true

backup:
  enabled: true
  schedule: 30 21 * * * # 9:30 PM UTC

ctdapp:
  core:
    replicas: 1
    # see https://console.cloud.google.com/artifacts/docker/hoprassociation/europe-west3/docker-images/cover-traffic?inv=1&invt=AbpZVw&project=hoprassociation
    tag: v3.9.0

  nodes:
    NODE_ADDRESS_1: http://ctdapp-blue-node-1-p2p-tcp:3001
    NODE_ADDRESS_2: http://ctdapp-blue-node-2-p2p-tcp:3001
    NODE_ADDRESS_3: http://ctdapp-blue-node-3-p2p-tcp:3001
    NODE_ADDRESS_4: http://ctdapp-blue-node-4-p2p-tcp:3001
    NODE_ADDRESS_5: http://ctdapp-blue-node-5-p2p-tcp:3001

deployment:
  resources: |
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi
