blue-nodes:
  enabled: true
green-nodes:
  enabled: true

backup:
  enabled: true
  schedule: 30 21 * * * # 9:30 PM UTC

ctdapp:
  core:
    replicas: 1
    tag: 104e764
    extraEnvVars:
      GCP_BUCKET: hoprnet-ctdapp-staging

      ECONOMIC_MODEL_FILENAME: parameters-staging.json

      CHANNEL_MIN_BALANCE: "0.05"
      CHANNEL_FUNDING_AMOUNT: "0.2"
      CHANNEL_MAX_AGE_SECONDS: "172800"
  postman:
    replicas: 1
    tag: 104e764
  nodes:
    NODE_ADDRESS_1: http://ctdapp-blue-node-1.ctdapp.svc:3001
    NODE_ADDRESS_2: http://ctdapp-blue-node-2.ctdapp.svc:3001
    NODE_ADDRESS_3: http://ctdapp-blue-node-3.ctdapp.svc:3001
    NODE_ADDRESS_4: http://ctdapp-blue-node-4.ctdapp.svc:3001
    NODE_ADDRESS_5: http://ctdapp-blue-node-5.ctdapp.svc:3001