blue-nodes:
  enabled: true
green-nodes:
  enabled: false

backup:
  enabled: true
  schedule: 30 21 * * * # 9:30 PM UTC

ctdapp:
  core:
    replicas: 1
    tag: v2.2.1
  postman:
    replicas: 1
    tag: v2.2.1
  nodes:
    NODE_ADDRESS_1: http://ctdapp-blue-node-1:3001
    NODE_ADDRESS_2: http://ctdapp-blue-node-2:3001
    NODE_ADDRESS_3: http://ctdapp-blue-node-3:3001
    NODE_ADDRESS_4: http://ctdapp-blue-node-4:3001
    NODE_ADDRESS_5: http://ctdapp-blue-node-5:3001
