legacy-nodes:
  enabled: true
blue-nodes:
  enabled: true
green-nodes:
  enabled: false

backup:
  enabled: true
  schedule: 30 21 * * * # 9:30 PM UTC

ctdapp:
  core:
    replicas: 1
    tag: v2.2.0
    extraEnvVars:
      FLAG_CORE_DISTRIBUTE_REWARDS: "1"

      DISTRIBUTION_MIN_ELIGIBLE_PEERS: "100"
      DISTRIBUTION_MAX_APR_PERCENTAGE: "15.0"
      
      GCP_BUCKET: hoprnet-ctdapp-prod

      ECONOMIC_MODEL_FILENAME: parameters-production.json


      CHANNEL_MIN_BALANCE: "15"
      CHANNEL_FUNDING_AMOUNT: "50"
      CHANNEL_MAX_AGE_SECONDS: "172800"
  postman:
    replicas: 1
    tag: v2.2.0
  nodes:
    NODE_ADDRESS_1: http://hoprd-ctdapp-1:3001
    NODE_ADDRESS_2: http://hoprd-ctdapp-2:3001
    NODE_ADDRESS_3: http://hoprd-ctdapp-3:3001
    NODE_ADDRESS_4: http://hoprd-ctdapp-4:3001
    NODE_ADDRESS_5: http://hoprd-ctdapp-5:3001
    NODE_ADDRESS_X: http://hoprd-ctdapp-5:3001