legacy-nodes:
  enabled: true
blue-nodes:
  enabled: true
green-nodes:
  enabled: false

ctdapp:
  image:
    core:
      tag: v2.1.9
    postman:
      tag: v2.1.9
  core:
    replicas: 1
    extraEnvVars:
      FLAG_CORE_HEALTHCHECK: "60"
      FLAG_CORE_CHECK_SUBGRAPH_URLS: "200"
      FLAG_CORE_GET_FUNDINGS: "900"
      FLAG_CORE_GET_TICKET_PRICE: "900"
      FLAG_CORE_AGGREGATE_PEERS: "300"
      FLAG_CORE_GET_TOPOLOGY_DATA: "300"
      FLAG_CORE_GET_SUBGRAPH_DATA: "300"
      FLAG_CORE_GET_REGISTERED_NODES: "300"
      FLAG_CORE_GET_NFT_HOLDERS: "900"
      FLAG_CORE_APPLY_ECONOMIC_MODEL: "600"
      FLAG_CORE_DISTRIBUTE_REWARDS: "1"

      FLAG_NODE_HEALTHCHECK: "60"
      FLAG_NODE_RETRIEVE_PEERS: "300"
      FLAG_NODE_RETRIEVE_OUTGOING_CHANNELS: "600"
      FLAG_NODE_RETRIEVE_INCOMING_CHANNELS: "600"
      FLAG_NODE_RETRIEVE_BALANCES: "900"
      FLAG_NODE_OPEN_CHANNELS: "900"
      FLAG_NODE_CLOSE_OLD_CHANNELS: "900"
      FLAG_NODE_CLOSE_PENDING_CHANNELS: "1800"
      FLAG_NODE_FUND_CHANNELS: "900"
      FLAG_NODE_GET_TOTAL_CHANNEL_FUNDS: "900"

      DISTRIBUTION_MIN_ELIGIBLE_PEERS: "100"
      DISTRIBUTION_MAX_APR_PERCENTAGE: "15.0"

      PEER_MIN_VERSION: "2.0.7"

      GCP_FILE_PREFIX: expected_reward
      GCP_FOLDER: expected_rewards
      GCP_BUCKET: hoprnet-ctdapp-prod

      ECONOMIC_MODEL_FILENAME: parameters-production.json
      ECONOMIC_MODEL_MIN_SAFE_ALLOWANCE: "-1"
      ECONOMIC_MODEL_NFT_THRESHOLD: "-1"

      CHANNEL_MIN_BALANCE: "15"
      CHANNEL_FUNDING_AMOUNT: "50"
      CHANNEL_MAX_AGE_SECONDS: "172800"

      RABBITMQ_TASK_NAME: send_1_hop_message
      RABBITMQ_PROJECT_NAME: ct-app

      LEGACY_SUBGRAPH_PAGINATION_SIZE: "1000"
      LEGACY_SUBGRAPH_SAFES_BALANCE_QUERY: "{ safes(first: valfirst, skip: valskip) { registeredNodesInNetworkRegistry { node { id } safe { id balance { wxHoprBalance } allowance { wxHoprAllowance } } } } }"
      LEGACY_SUBGRAPH_WXHOPR_TXS_QUERY: "{ transactions(where: { from: valfrom, to: valto }) { from to amount }} "
      LEGACY_SUBGRAPH_FROM_ADDRESS: 0xd9a00176cf49dfb9ca3ef61805a2850f45cb1d05
  postman:
    replicas: 1
    extraEnvVars:
      PARAM_BATCH_SIZE: "200"
      PARAM_DELAY_BETWEEN_TWO_MESSAGES: "0.2"
      PARAM_MESSAGE_DELIVERY_TIMEOUT: "15"
      PARAM_MAX_ATTEMPTS: "6"
      RABBITMQ_PROJECT_NAME: ct-app