replicas: 5
network: rotsee
# testing with connectivity debug logging, this is based on 2.2.3
version: 2.2.3-pr.6869

service:
  type: LoadBalancer

deployment:
  env: |
    - name: HOPR_INTERNAL_LIBP2P_MSG_ACK_MAX_TOTAL_STREAMS
      value: "10000"
  #   - name: RUST_LOG
  #     value: debug,libp2p_swarm=debug,libp2p_mplex=debug,multistream_select=debug,libp2p_tcp=debug,libp2p_dns=info,sea_orm=info,sqlx=info
config: |
  hopr:
    chain:
      network: rotsee
    strategy:
      on_fail_continue: true
      allow_recursive: false
      strategies: []
    protocol:
      outgoing_ticket_winning_prob: 0.000125
      outgoing_ticket_price: "200 HOPR"
  inbox:
    capacity: 16384

identityPool:
  funding:
    schedule: 30 8 * * 1

identities:
  ctdapp-green-node-1:
    identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiI3YTU4MzJjYzhkMWNkYmE3Y2FkM2Y1MDM4MTc2ZWZhMCJ9LCJjaXBoZXJ0ZXh0IjoiZTAyZjAwYTlkNjY1NzA3Nzk5OGNhYzIzZjMzMzc5NmY1N2JjZTBlMWI2NWYwMWMxMWQ4ZGRkNGUzMTE1OGUwMDFhNDhkODNkYjcxNWVjNzhkNjJhODA2Mzk3OGE3NDM3OGZmNjQ4YzM3MzU0YTQ3MzcyNzFiY2E4YTVjMzY4NGNhZDQyM2Q4MmI5OWQ0ZTE5MzVkZjZjOTQ2ZjY4NzA1YzhmZWIzZGY2ZDYwMzhjZmFiZjZlY2I3Njc0MDM3ZWU2ZThlMDUwYzRlNGE3YTk5MDEyYzE3ZmViYzk3N2U5ZjNiYjFjYWNmMGYyZTQ0ZWFkYTA4Y2JhYmI2ZWRiMGE0MjAzZDExODZhYTBlNzE0Njk5NTEzMGU5YzZhZDRlMDNmNWRkZjFmZGMzNzMzYWY5MmM1NzJmODMyODNjN2RmZDhiYTlkNjhmNjQ0MTAwNjJhMTM1MWQ3ZTkiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiY2FhYzc5MmRkNjY2YWViNzFiMWE1ZDcyOTA1MDM4ZjViMWEzMDE5Y2U5NWJmODQ2MmU2ZmZlYzVkOWNmYWU4ZiJ9LCJtYWMiOiI3MmE5Mjg1OGU1ZjZkYjc2NjQyOGE2NGRlMjhmNDdhMTczN2FkMzlkZmRjZDljNjA3MjkxNzczMTgxYzliOGMzIn0sImlkIjoiNzIzYjdmOGQtNWZiMC00MjQzLWIyZDAtYjAxMmRmNWYwMzVkIiwidmVyc2lvbiI6M30="
    peerId: "12D3KooWQsns4Cfimb67yzYRStdf2ctZDASRCF7wda1xf1fH7yZ5"
    nativeAddress: "0xac3c2d1f751d9c763be29aabb20cf31295f3ea27"
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-2:
    identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJiNzIyNmNjMDdmYjg1YmM3MjgzYzk3NGM1YjY3ZGUxMyJ9LCJjaXBoZXJ0ZXh0IjoiZDk0YWNiMWU0ZjQyOTc3NDhjYmQ0NTdkMjEwZDQ2YmYxZjY4NmQyYjc0YzBiMmY0YTViMTQ0Y2RjNzdjNDM3N2JmZmNjMzFjNTc3MDhjYzViZDQ0NGNiODI5YjEzZjI4YWY2MzM0MTc0NGZmMTA3MDU0MDI3Yzc1NGE0ZDg1Mjg2N2IzZWQxOWFlYjY3MGRkNjI3YWJlYzRlN2VjODNjYjk1ZDQ2MTY4NzUyMWJhZDRlYmNjNjE1NWQ3MWYxOWQ1MGQzOGNiY2Q1YjU1ZDNiMDI4YzRmZDRhZTkwODI1MzQ1MjRmYWNhYWI3YjAzMjM4Y2I0MDU2MmI3ZTZlNjEzNmVkMjYwMDgzYTcxYzFmNjJkNTIzMWM1ZGI3NjUzZGUwZjQ5N2RjZmM1Yjg3ZjhkZDY4MWFmZTVjNGY1NTcxOGZjMDBiZDI2NzBjOTMxYjU2NzdhOGEyOTMiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiMjlmOGVhZDY3ZDUwMjc3NjVkZjI4ZjMwOGQ1OGRkNzY4MDI4OGZhMjVjMTZjOWRiMzQ4YmJmOTdhZDFmZGM1YiJ9LCJtYWMiOiI5ZjM2YjJkZGI1YjI2NTRmMzQzMmViOWE4MmZiMzFjZDNjYjgxNDM2N2E3MTlmOGQyMGM1ODY0OGIwNTQyMTg2In0sImlkIjoiZjhkOGY3M2YtNGFiYy00MzFmLTg3NzUtMTZhYWNkNzRhM2JhIiwidmVyc2lvbiI6M30="
    peerId: "12D3KooWE4jdUDg8tTk2NQTxkM8fkxbX7HfL7VLhz1Qr8okGKrRa"
    nativeAddress: "0x154a32241dacd34c55ca65c2dfdef173d6d9e7f3"
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-3:
    identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJmNzA5MjdmZjEzMTQyOTYwNWJkZWE0Y2YzZDQ0ZDNiMyJ9LCJjaXBoZXJ0ZXh0IjoiOTY0Mzk2MzM4NWJiMWZiODViZDViZWE1NTI1ZWQ2Yjg5MmIyMDExNTcyZjQ2OTk1OTM1ODRlMjNmMWZiNDhjZmEzMTY1YzA5NmY0YjBiM2ZkODM1NDk5OWNkODQxZDE5YzRkMGU3YTA1Nzc3ODM5OWVjMmYyZTUyMDA1NGYxN2UxZjA2ZTFlNDAyNWFjYWM4ZTgyYTA1ZmY2YjQwZTUyOWVjN2MwYWZmZTQ2MGE5ZjM4ZGMyN2MzZWRlNTQ0NTBlY2RiMWZiMThiMjg2ZGY3MDJlMWFjYjRlNDg3NjlmM2RkNGFjYjBkMjkyMzI5NjBhZTdkY2E4NTA3MDVlMzMyOWE5NWI5ZWMyZjQxMTk3NjllMDYwY2U1MTM4NmUwOGQwYjNlNzU0ZTFhZDRkOWJkYzYwZWFmNmM2OWI5NmQ4YzMzOGQ2MDBmYmY2OWJiYzhlOGU3MTRmOWYiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiMjA5NzQ4ZjhjMzdjYWEwMGY2MjhiOTQ1ZTMxMDRjMGJlZGFlNjM4MzM0YTA1NzBiOTFjMmYyZTBkNzQ0YTNlOCJ9LCJtYWMiOiI1MzNiNzRiMzAwZWVjYzNiYTdkMmQ0ZmMwYzI4Njc1ZmQyZDM5M2RmNzE0YzY0NWYwZjVmNTRhYmVjZThkYzVkIn0sImlkIjoiMjYxODg1MmUtODExNy00NDEwLTgzMGYtZWM4YTgwMGYxNGZjIiwidmVyc2lvbiI6M30="
    peerId: "12D3KooWGSxyZi99kPvvzqUnwSCfwGf3o5VHV7eSvbv1w34Sdouh"
    nativeAddress: "0x7673daf47ae218d7d9b2fa0e8fc397c2a6940bc1"
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-4:
    identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJmZTllNmQyYWVmNzIzYmUyNzIxM2FjNzM4OGMwNDVhMiJ9LCJjaXBoZXJ0ZXh0IjoiZTA2MGRiYTFhMjJmZjRjZGJiM2VhZWVkZGY3ZTFjZmFlNDEzNWE2NzU4Zjc2ZmI3ODNiMDVkMjViMmJmODhhNGE2NTExOGY5ZDIyYjE3YjBlZWU5NmJiMzcxODgxNjBmOThjYjcwMTQ1OWRmYTkyMzg5YzJkMmY4NmY5Y2YxZmU0ZGY2NDY0ZTNjNWJiN2UxZDE4M2M3ZWIzY2QzZTk4ZTk4NTZhNzc3OGQxMmRiMGM1ZDZjMDk5ODc1MDVhOGJlNmZjMWI4NmRiMWJmZjBkMWYzZjlmNWEzMTE3YjRhOGU1YTFhYzc4NmM0NWU4MGM5YmE4MDhlNjRkYzk4ZjIzOTIyNzdmYWM0Y2NlOWRmZGZmMTU0ZDBiNTE4OTc3ZDJjM2Y3YmZhMGFmYWYzZDc0M2RlMzVkMjQzMjgxNmM5ZmE4NmIzNDI0OGRmM2M5ZWMyNTUwODcwMzUiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiM2JjZjZhMjVjZjJiMjZiZTUzMTI5OGQ2Zjk3ODFiMWI2YzRjYmI1ODZmMmI4MjI1N2QzYmY5ODQwZWM2MDA4OSJ9LCJtYWMiOiJiMWEwMzE1OWM0MzhiN2IyMTZjZmZmYjFiOTk4M2NiZDRkNGMzZGRhZjBjYmIyYTliYjI1M2NlNWRiZjdiN2QxIn0sImlkIjoiYjg5NTY2ZTQtNmViYi00MGFmLThiNTktNDc4MmQ2MGRlMTFmIiwidmVyc2lvbiI6M30="
    peerId: "12D3KooWQqxFfz7CgT2xuf3exSd8vyav45CUzUSokCj8y7GidRgr"
    nativeAddress: "0xc2421cc4e9b3eeaefea2d87d2ee3dde9cc772e8a"
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
  ctdapp-green-node-5:
    identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJiYTY0ZDVkM2ZjNzJmNzI2MDQyYmJjYTI1YzVjYWFhMCJ9LCJjaXBoZXJ0ZXh0IjoiNDdlMzUwMGIyYTcyYzQ5YWUxYWViZWJiZmNiZTRhMTg2ODY0MTcxZTRjYTQ2NGM1YzJiZGU0NGFhOTcwZWZmZWNjMWIyMjQ4YWEwNjNlMjNhNmI0M2NlMWJkMDk4NGFkOGY2MDgyNTllOGZhYWY3Yzk3NzAwMTAxMWU1YmJkMmFkMDUzMjdlNWMzMTBkNmM0MDc5MWU3YTNhZDBlMGRhNzY5MzU5NTM5YjcyZjJmNDQ3OGUwMmFhNjE2YWQ5YWU5NDYzZDM5NTVhZmQ1OWM0YmU3ZjUyMDYyYjI2ZDQ3MDczYTVjNGU3ZjNkMzc1NGE3ODQ5ODJiOGUyODc5Yzc0MGY3NmEyZDFlYjhiNjRjMWUwYzgwMWUxMjcxNGVlMzZjOTUyNDA0NTAxY2JjODYzOWUwY2Q0Y2E0MmZiN2VkYjE0OGI0OTVmODg1MGM2OGQ4MGY2YTFkYmUiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiOWNmZDMyZWZmYzEzZWVmODRkZTZiNzM3MWJkZmIxYjA3MzJlZTZkYzY2MTQxMWY5NTUwZTdmZTg1NTZkZTc4YiJ9LCJtYWMiOiJiMDkwOTg4OTBkMzM1MzMxOGI3ZTk2ZDc3YzYzMTE3NTlhMzVkOTkxM2Q4OGQ5Y2M5YjJiMDliMjUwYzliNjA3In0sImlkIjoiMDlkYTA5YzktNDM3ZS00YTZmLTg1YzItNjhhYWY2MTdlYzg4IiwidmVyc2lvbiI6M30="
    peerId: "12D3KooWDpupMFX3cnEcxLsbYBBz8gJ2mR9zxkZyzbRSTm3YPhRU"
    nativeAddress: "0x4b306f6a7fee6cbfdab11645b81337cbaab59900"
    safeAddress: "0x6f835DeD9E11B859DE87bACBbec9E2BE13Fe0190"
    moduleAddress: "0x954787c8BE35e8Fe080bd1A978E54FD92114313A"
