apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: postman-config
data:
  CONFIG_FILE_PATH: ./scripts/core_{{ .Values.environmentName }}_config.yaml
  {{- if .Values.ctdapp.postman.extraEnvVars -}}
  {{ .Values.ctdapp.postman.extraEnvVars | toYaml | nindent 2 }}
  {{- end }}