apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: core-config
data:
  FLAG_CORE_HEALTHCHECK: "60"
  FLAG_CORE_CHECK_SUBGRAPH_URLS: "200"
  FLAG_CORE_GET_FUNDINGS: "900"
  FLAG_CORE_GET_TICKET_PRICE: "900"
  FLAG_CORE_AGGREGATE_PEERS: "300"
  FLAG_CORE_GET_TOPOLOGY_DATA: "300"
  FLAG_CORE_GET_SUBGRAPH_DATA: "300"
  FLAG_CORE_GET_REGISTERED_NODES: "300"
  FLAG_CORE_GET_NFT_HOLDERS: "900"
  FLAG_CORE_APPLY_ECONOMIC_MODEL: "600"

  FLAG_NODE_HEALTHCHECK: "60"
  FLAG_NODE_RETRIEVE_PEERS: "300"
  FLAG_NODE_RETRIEVE_OUTGOING_CHANNELS: "600"
  FLAG_NODE_RETRIEVE_INCOMING_CHANNELS: "600"
  FLAG_NODE_RETRIEVE_BALANCES: "900"
  FLAG_NODE_OPEN_CHANNELS: "900"
  FLAG_NODE_CLOSE_OLD_CHANNELS: "900"
  FLAG_NODE_CLOSE_PENDING_CHANNELS: "1800"
  FLAG_NODE_FUND_CHANNELS: "900"
  FLAG_NODE_GET_TOTAL_CHANNEL_FUNDS: "900"

  DISTRIBUTION_MIN_ELIGIBLE_PEERS: "100"
  DISTRIBUTION_MAX_APR_PERCENTAGE: "15.0"

  PEER_MIN_VERSION: "2.0.7"

  GCP_FILE_PREFIX: expected_reward
  GCP_FOLDER: expected_rewards

  ECONOMIC_MODEL_MIN_SAFE_ALLOWANCE: "-1"
  ECONOMIC_MODEL_NFT_THRESHOLD: "-1"

  RABBITMQ_TASK_NAME: send_1_hop_message
  RABBITMQ_PROJECT_NAME: ct-app
  {{- if .Values.ctdapp.core.extraEnvVars -}}
  {{ .Values.ctdapp.core.extraEnvVars | toYaml | nindent 2 }}
  {{- end }}