---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: ctdapp
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  permissions:
    configure: .*
    read: .*
    write: .*
  userReference:
    name: ctdapp
  vhost: ctdapp
  rabbitmqClusterReference:
    name: rabbitmq-ha-cluster