apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: subgraph
data:
  SUBGRAPH_STAKING_URL: {{ .Values.ctdapp.subgraph.stakingUrl | b64enc }}
  SUBGRAPH_STAKING_URL_BACKUP: {{ .Values.ctdapp.subgraph.stakingUrlBackup | b64enc }}
  SUBGRAPH_SAFES_BALANCE_URL: {{ .Values.ctdapp.subgraph.safesBalanceUrl | b64enc }}
  SUBGRAPH_SAFES_BALANCE_URL_BACKUP: {{ .Values.ctdapp.subgraph.safesBalanceUrlBackup | b64enc }}
  SUBGRAPH_WXHOPR_TXS_URL: {{ .Values.ctdapp.subgraph.wxhoprTxsUrl | b64enc }}
  SUBGRAPH_WXHOPR_TXS_URL_BACKUP: {{ .Values.ctdapp.subgraph.wxhoprTxsUrlBackup | b64enc }}
