apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    replicator.v1.mittwald.de/replicate-to: ctdapp
  name: rabbitmq-ctdapp
  namespace: rabbitmq
data:
    CELERY_BROKER_URL: {{ .Values.ctdapp.rabbitmq.celeryBrokerUrl | b64enc }}
    RABBITMQ_HOST: {{ .Values.ctdapp.rabbitmq.host | b64enc }}
    RABBITMQ_PASSWORD: {{ .Values.ctdapp.rabbitmq.password | b64enc }}
    RABBITMQ_USERNAME: {{ .Values.ctdapp.rabbitmq.username | b64enc }}
    RABBITMQ_VIRTUALHOST: {{ .Values.ctdapp.rabbitmq.virtualhost | b64enc }}
    password: {{ .Values.ctdapp.rabbitmq.password | b64enc }}
    username: {{ .Values.ctdapp.rabbitmq.username | b64enc }}
