apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: postgres
data:
  PGDATABASE: {{ .Values.ctdapp.postgres.database | b64enc }}
  PGHOST: {{ .Values.ctdapp.postgres.host | b64enc }}
  PGPASSWORD: {{ .Values.ctdapp.postgres.password | b64enc }}
  PGPORT: {{ .Values.ctdapp.postgres.port | b64enc }}
  PGUSER: {{ .Values.ctdapp.postgres.username | b64enc }}
