apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: hoprd-nodes
data:
    NODE_KEY_1: {{ .Values.wallet.hoprdApiToken | b64enc }}
    NODE_KEY_2: {{ .Values.wallet.hoprdApiToken | b64enc }}
    NODE_KEY_3: {{ .Values.wallet.hoprdApiToken | b64enc }}
    NODE_KEY_4: {{ .Values.wallet.hoprdApiToken | b64enc }}
    NODE_KEY_5: {{ .Values.wallet.hoprdApiToken | b64enc }}


