---
{{- if .Values.backup.enabled }}
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: sa-backup
  annotations:
    iam.gke.io/gcp-service-account: "backup@hopr-{{ .Values.environmentName }}.iam.gserviceaccount.com"
{{- end }}%  
