apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ include "ctdapp.fullname" . }}
  labels:
    {{- include "ctdapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ctdapp.service.type }}
  ports:
    - port: {{ .Values.ctdapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ctdapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
