apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ct-core
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: ctdapp
      app.kubernetes.io/component: core
