{{- if .Values.ctdapp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ctdapp.serviceAccountName" . }}
  labels:
    {{- include "ctdapp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- with .Values.ctdapp.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ctdapp.serviceAccount.automount }}
{{- end }}
