---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ctdapp
  namespace: rabbitmq
spec:
  importCredentialsSecret:
    name: rabbitmq-ctdapp
  rabbitmqClusterReference:
    name: rabbitmq-ha-cluster
