---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ctdapp
  namespace: rabbitmq
spec:
  name: ctdapp
  rabbitmqClusterReference:
    name: rabbitmq-ha-cluster