---
name: Merge
on:
  pull_request:
    types:
      - closed
      # - synchronize
    branches:
      - main
concurrency:
  group: merge-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-docker:
    name: Docker
    if: github.event.pull_request.merged == true
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@build-docker-v2
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      version_type: pr
      build_matrix: >-
        [
          {
            "runner": "depot-ubuntu-24.04-4",
            "architecture": "x86_64-linux",
            "build_command": "cd ct-app && nix run .#docker-x86_64-linux"
          }
        ]
      cachix_cache_name: ct-dapp
      build_file: ct-app/pyproject.toml
      docker_image_name: cover-traffic
      deployment_namespace: ctdapp
      deployment_label_selector: "hoprds.hoprnet.org/cluster=${{ vars.CTDAPP_STAGING_DEPLOYMENT_CLUSTER }}"
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  notify:
    name: Notify failure
    needs:
      - build-docker
    if: ${{ always() && failure() }}
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Notify failed merge pipeline
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "HOPRd"
          topic: "Core"
          content: |
            The merge pipeline has failed for pull request [#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
